### ISSUE TITLE
QGIS OpenGeo Explorer: Cannot handle two layers with the same name but different workspaces

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/suite#843] opened 2015-01-14 20:13 UTC
Cannot display two layers with the same name but different workspaces:

"There are several layers with this name in the catalog. This results in an ambiguous situation and unfortunately we cannot differentiate between them. Only one layer is displayed.This element represents the layer based on a datastore from the opengeo workspace" 

(Tested on OS X 10.10, QGIS 2.6.1)

**Comment by volaya** [comment] 2015-01-15 17:55
Not a bug. It is a limitation of the GeoServer REST API, which does not provide workspace info.

This limitation is described in the plugin help. Nothing we can do in the plugin until this is fixed in GeoServer (the GeoServer team is already aware of it and has discussed its implementation)

**Closed by volaya** 2015-01-15 17:55 UTC
Labels: QGIS

**Comment by tbarsballe** [comment] 2015-01-19 20:49
This issue was moved to boundlessgeo/suite-qgis-plugin#165
