### ISSUE TITLE
QGIS Opengeo Explorer: Cannot delete a workspace containing a layer

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/suite#844] opened 2015-01-14 20:15 UTC
QGIS 2.6.1, OS X 10.10

Python error when trying to delete a workspace containing a layer (Also occurs when trying to delete the layer or the store): https://gist.github.com/tbarsballe/1a4395b9ef486013c987

(Tested on OS X 10.10, QGIS 2.6.1)

**Comment by volaya** [comment] 2015-01-16 07:00
Not able to reproduce it, but I have seen a possible case and fixed it in here. It doesn't see to be breaking anything else, and deleting elements works fine. The error you were seeing should not be possible now.

The fix is in the plugin repo, please test from there

**Comment by tbarsballe** [comment] 2015-01-19 19:05
That seems to have fixed it, I am not getting the error anymore.

Also, when building the plugin locally, I ran into some issues with the docs. See fixes here: https://github.com/boundlessgeo/suite-qgis-plugin/pull/156

**Closed** 2015-01-19 19:05 UTC

**Comment by tbarsballe** [comment] 2015-01-19 20:48
This issue was moved to boundlessgeo/suite-qgis-plugin#164
